package cli_test

import (
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestPHPCommandCreatesAndRepairsManagedConfigurationWithoutChangingArguments(t *testing.T) {
	artifact := fakeRuntimeArtifact(t)
	server := httptest.NewServer(http.HandlerFunc(func(response http.ResponseWriter, _ *http.Request) {
		_, _ = response.Write(artifact)
	}))
	manifest := writeRuntimeCommandManifest(t, server.URL+"/runtime.zip", bytesSHA256(artifact))
	binary := buildPhiteWithManifest(t, manifest)
	cache := filepath.Join(t.TempDir(), "runtime-cache")
	environment := append(os.Environ(), "PHITE_RUNTIME_CACHE="+cache, "PHPRC="+filepath.Join(t.TempDir(), "host.ini"), "PHP_INI_SCAN_DIR="+filepath.Join(t.TempDir(), "host-scan"))

	command := exec.Command(binary, "php", "--fixture-argument")
	command.Env = environment
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("run PHP with Managed Configuration: %v\n%s", err, output)
	}
	if !strings.Contains(string(output), `args=["--fixture-argument"]`) {
		t.Fatalf("Managed Configuration changed PHP arguments: %s", output)
	}
	configuration := outputLineValue(t, string(output), "phprc=")
	absoluteCache, err := filepath.Abs(cache)
	if err != nil {
		t.Fatalf("resolve cache: %v", err)
	}
	relative, err := filepath.Rel(absoluteCache, configuration)
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		t.Fatalf("Managed Configuration is outside Runtime Cache: %q", configuration)
	}
	original, err := os.ReadFile(configuration)
	if err != nil {
		t.Fatalf("read Managed Configuration: %v", err)
	}
	if !strings.Contains(string(original), "Generated by Phite") {
		t.Fatalf("Managed Configuration lacks ownership marker: %s", original)
	}
	scanDirectory := outputLineValue(t, string(output), "scan=")
	scanRelative, err := filepath.Rel(absoluteCache, scanDirectory)
	if err != nil || scanRelative == ".." || strings.HasPrefix(scanRelative, ".."+string(filepath.Separator)) {
		t.Fatalf("Managed PHP scan directory is outside Runtime Cache: %q", scanDirectory)
	}
	entries, err := os.ReadDir(scanDirectory)
	if err != nil || len(entries) != 0 {
		t.Fatalf("Managed PHP scan directory must be empty: entries=%d err=%v", len(entries), err)
	}

	if err := os.WriteFile(configuration, []byte("extension=untrusted.dll\n"), 0o600); err != nil {
		t.Fatalf("tamper Managed Configuration: %v", err)
	}
	server.Close()
	second := exec.Command(binary, "php", "--fixture-argument")
	second.Env = environment
	if output, err := second.CombinedOutput(); err != nil {
		t.Fatalf("repair Managed Configuration offline: %v\n%s", err, output)
	}
	repaired, err := os.ReadFile(configuration)
	if err != nil {
		t.Fatalf("read repaired Managed Configuration: %v", err)
	}
	if string(repaired) != string(original) {
		t.Fatalf("Managed Configuration was not restored\nwant:\n%s\ngot:\n%s", original, repaired)
	}
}

func outputLineValue(t *testing.T, output, prefix string) string {
	t.Helper()
	for _, line := range strings.Split(output, "\n") {
		if strings.HasPrefix(line, prefix) {
			return strings.TrimPrefix(line, prefix)
		}
	}
	t.Fatalf("output lacks %q line: %s", prefix, output)
	return ""
}
