package managedruntime

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	goruntime "runtime"
	"sort"
	"strings"
)

const (
	phpConfigurationName = "php.ini"
	phpScanDirectoryName = "ini-scan"
)

type phpExtensionRule struct {
	directive string
	library   string
}

var windowsSharedExtensionRules = map[string]phpExtensionRule{
	"curl":       {directive: "extension", library: "php_curl.dll"},
	"fileinfo":   {directive: "extension", library: "php_fileinfo.dll"},
	"intl":       {directive: "extension", library: "php_intl.dll"},
	"mbstring":   {directive: "extension", library: "php_mbstring.dll"},
	"openssl":    {directive: "extension", library: "php_openssl.dll"},
	"pdo_sqlite": {directive: "extension", library: "php_pdo_sqlite.dll"},
	"sqlite3":    {directive: "extension", library: "php_sqlite3.dll"},
	"zip":        {directive: "extension", library: "php_zip.dll"},
}

// Environment returns a child environment isolated from host PHP ini paths.
func (installation Installation) Environment(base []string) []string {
	return managedPHPEnvironment(base, installation.configuration, installation.scanDirectory)
}

func (manager *Manager) ensurePHPConfiguration(runtimeDirectory string) (string, string, error) {
	configurationPath := filepath.Join(manager.directory, phpConfigurationName)
	scanDirectory := filepath.Join(manager.directory, phpScanDirectoryName)
	if err := ensureEmptyScanDirectory(scanDirectory); err != nil {
		return "", "", err
	}
	contents, hasSharedExtensions, err := manager.phpConfiguration(runtimeDirectory)
	if err != nil {
		return "", "", err
	}
	current, err := os.ReadFile(configurationPath)
	if err != nil || !bytes.Equal(current, contents) {
		if err != nil && !os.IsNotExist(err) {
			return "", "", fmt.Errorf("inspect Managed PHP configuration: %w", err)
		}
		if err := replaceConfiguration(configurationPath, contents); err != nil {
			return "", "", err
		}
	}
	if hasSharedExtensions {
		phpPath := manager.phpPath(runtimeDirectory)
		if err := manager.verifyPHPModules(phpPath, configurationPath, scanDirectory); err != nil {
			return "", "", err
		}
	}
	return configurationPath, scanDirectory, nil
}

func (manager *Manager) phpConfiguration(runtimeDirectory string) ([]byte, bool, error) {
	var configuration strings.Builder
	configuration.WriteString("; Generated by Phite from the verified Runtime Identity. Changes will be replaced.\n")
	configuration.WriteString("[PHP]\n")
	if manager.runtime.Identity.OS != "windows" {
		return []byte(configuration.String()), false, nil
	}

	var rules []phpExtensionRule
	for _, extension := range manager.runtime.Identity.Extensions {
		if rule, ok := windowsSharedExtensionRules[strings.ToLower(extension)]; ok {
			rules = append(rules, rule)
		}
	}
	if len(rules) == 0 {
		return []byte(configuration.String()), false, nil
	}

	extensionDirectory := filepath.Join(runtimeDirectory, "ext")
	info, err := os.Stat(extensionDirectory)
	if os.IsNotExist(err) {
		return nil, false, errors.New("Managed Runtime is missing its declared shared extension directory")
	}
	if err != nil {
		return nil, false, fmt.Errorf("inspect Managed Runtime extension directory: %w", err)
	}
	if !info.IsDir() {
		return nil, false, errors.New("Managed Runtime extension path is not a directory")
	}
	escapedDirectory := strings.ReplaceAll(filepath.ToSlash(extensionDirectory), `"`, `\"`)
	fmt.Fprintf(&configuration, "extension_dir=\"%s\"\n", escapedDirectory)
	for _, rule := range rules {
		libraryPath := filepath.Join(extensionDirectory, rule.library)
		info, err := os.Stat(libraryPath)
		if os.IsNotExist(err) {
			return nil, false, fmt.Errorf("Managed Runtime is missing declared shared extension %s", rule.library)
		}
		if err != nil {
			return nil, false, fmt.Errorf("inspect Managed PHP extension %s: %w", rule.library, err)
		}
		if info.IsDir() {
			return nil, false, fmt.Errorf("Managed PHP extension %s is not a file", rule.library)
		}
		fmt.Fprintf(&configuration, "%s=%s\n", rule.directive, rule.library)
	}
	return []byte(configuration.String()), true, nil
}

func (manager *Manager) verifyPHPModules(phpPath, configurationPath, scanDirectory string) error {
	command := exec.Command(phpPath, "-c", configurationPath, "-m")
	command.Env = managedPHPEnvironment(os.Environ(), configurationPath, scanDirectory)
	var stderr bytes.Buffer
	command.Stderr = &stderr
	output, err := command.Output()
	if err != nil {
		return fmt.Errorf("verify Managed PHP extensions: %w: %s", err, strings.TrimSpace(stderr.String()))
	}
	expected := make(map[string]string, len(manager.runtime.Identity.Extensions))
	for _, extension := range manager.runtime.Identity.Extensions {
		expected[strings.ToLower(extension)] = extension
	}
	actual := make(map[string]string)
	for _, line := range strings.Split(string(output), "\n") {
		module := strings.TrimSpace(line)
		if module == "" || strings.HasPrefix(module, "[") {
			continue
		}
		actual[strings.ToLower(module)] = module
	}
	var difference []string
	for key, extension := range expected {
		if _, ok := actual[key]; !ok {
			difference = append(difference, "missing "+extension)
		}
	}
	for key, extension := range actual {
		if _, ok := expected[key]; !ok {
			difference = append(difference, "unexpected "+extension)
		}
	}
	if len(difference) != 0 {
		sort.Strings(difference)
		return fmt.Errorf("Managed PHP extension set differs from Runtime Identity: %s", strings.Join(difference, ", "))
	}
	return nil
}

func ensureEmptyScanDirectory(path string) error {
	if err := os.MkdirAll(path, 0o700); err != nil {
		return fmt.Errorf("create Managed PHP scan directory: %w", err)
	}
	entries, err := os.ReadDir(path)
	if err != nil {
		return fmt.Errorf("inspect Managed PHP scan directory: %w", err)
	}
	if len(entries) != 0 {
		return errors.New("Managed PHP scan directory is not empty")
	}
	return nil
}

func managedPHPEnvironment(base []string, configurationPath, scanDirectory string) []string {
	environment := make([]string, 0, len(base)+2)
	for _, entry := range base {
		key, _, _ := strings.Cut(entry, "=")
		if phpEnvironmentKeyEqual(key, "PHPRC") || phpEnvironmentKeyEqual(key, "PHP_INI_SCAN_DIR") {
			continue
		}
		environment = append(environment, entry)
	}
	environment = append(environment, "PHPRC="+configurationPath)
	return append(environment, "PHP_INI_SCAN_DIR="+scanDirectory)
}

func phpEnvironmentKeyEqual(left, right string) bool {
	if goruntime.GOOS == "windows" {
		return strings.EqualFold(left, right)
	}
	return left == right
}

func replaceConfiguration(path string, contents []byte) error {
	temporary, err := os.CreateTemp(filepath.Dir(path), ".php-configuration-*")
	if err != nil {
		return fmt.Errorf("create temporary Managed PHP configuration: %w", err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o600); err != nil {
		temporary.Close()
		return fmt.Errorf("protect Managed PHP configuration: %w", err)
	}
	_, writeErr := temporary.Write(contents)
	syncErr := temporary.Sync()
	closeErr := temporary.Close()
	if err := errors.Join(writeErr, syncErr, closeErr); err != nil {
		return fmt.Errorf("write Managed PHP configuration: %w", err)
	}
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("replace Managed PHP configuration: %w", err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("publish Managed PHP configuration: %w", err)
	}
	return nil
}
